"""Generate frontend contract and real local API examples; --check detects drift."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from unittest.mock import patch


ROOT = Path(__file__).resolve().parent.parent


def _typescript(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(_typescript(part) for part in schema["anyOf"]))
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{_typescript(schema['items'])}>"
    if kind == "object":
        if "properties" in schema:
            required = set(schema.get("required", []))
            fields = [f"  {json.dumps(name)}{'' if name in required else '?'}: {_typescript(value)};"
                      for name, value in schema["properties"].items()]
            return "{\n" + "\n".join(fields) + "\n}"
        additional = schema.get("additionalProperties", {})
        return f"Record<string, {_typescript(additional) if isinstance(additional, dict) else 'unknown'}>"
    if kind in {"string", "boolean", "null", "number", "integer"}:
        return "number" if kind == "integer" else kind
    raise ValueError(f"Unsupported schema shape for TypeScript: {schema}")


def build_artifacts() -> dict[str, str]:
    # Keys can exist on a developer machine; export must never invoke a provider.
    with patch.dict(os.environ, {"AI_PROVIDER": "local", "RANKING_PROVIDER": "tfidf", "CORS_ALLOWED_ORIGINS": ""}):
        from fastapi.testclient import TestClient
        from .api import create_app
        from .demo import BASE, HOST

        app = create_app()
        schema = app.openapi()
        artifacts = {"integration/openapi.json": json.dumps(schema, ensure_ascii=False, indent=2) + "\n"}
        definitions = schema["components"]["schemas"]
        types = "// Generated by python -m contractor_match.export_contract. Do not edit.\n\n"
        types += "\n\n".join(f"export type {name} = {_typescript(definition)};"
                               for name, definition in sorted(definitions.items())) + "\n"
        artifacts["integration/api-types.d.ts"] = types
        samples = {
            "matched": HOST,
            "short_with_alternative": HOST | {"date": "2026-12-19"},
            "category_absent": BASE | {"city": "Астана", "category": "Декоратор"},
            "no_eligible": BASE | {"city": "Астана", "category": "Флорист", "budget_kzt": 100000},
            "brief_understanding": BASE | {"brief": "Нужен спокойный ведущий, без конкурсов, на русском"},
            "invalid_request": BASE | {"budget_kzt": "1200000"},
        }
        with TestClient(app) as client:
            for name, request in samples.items():
                response = client.post("/recommendations", json=request)
                example = {"request": request, "http_status": response.status_code, "response": response.json()}
                artifacts[f"integration/examples/{name}.json"] = json.dumps(example, ensure_ascii=False, indent=2) + "\n"
            response = client.get("/catalogue/options")
            artifacts["integration/examples/catalogue_options.json"] = json.dumps(response.json(), ensure_ascii=False, indent=2) + "\n"
        return artifacts


def main() -> int:
    parser = argparse.ArgumentParser(description="Экспорт контракта для фронтенда без внешнего AI")
    parser.add_argument("--check", action="store_true", help="Проверить актуальность без записи файлов")
    args = parser.parse_args()
    outdated = []
    for name, content in build_artifacts().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                outdated.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if outdated:
        print("Contract drift: " + ", ".join(outdated))
        return 1
    print("Frontend contract is current." if args.check else "Frontend contract exported.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
