// Generated by python -m contractor_match.export_contract. Do not edit.

export type Alternative = {
  "changes": Array<ConditionChange>;
  "request": RecommendationRequest;
  "eligible_count": number;
  "added_count": number;
  "candidate_ids": Array<string>;
  "message": string;
};

export type ApiError = {
  "code"?: "invalid_request" | "service_misconfigured" | "internal_error" | "not_found" | "method_not_allowed" | "http_error" | "catalogue_unavailable" | "request_too_large";
  "message"?: string;
  "details": Array<InputIssue>;
};

export type BriefUnderstanding = {
  "method"?: "local_rules";
  "styles"?: Array<string>;
  "unwanted"?: Array<string>;
  "languages"?: Array<"русский" | "казахский" | "английский">;
  "effective_language"?: "русский" | "казахский" | "английский" | null;
  "language_source"?: "field" | "brief" | "unspecified";
  "notes"?: Array<string>;
};

export type Card = {
  "id": string;
  "name": string;
  "category": string;
  "city": string;
  "price_from_kzt": number;
  "synthetic": boolean;
  "city_imputed": boolean;
  "price_imputed": boolean;
  "explanation": string;
  "evidence_quote": string;
  "evidence_note"?: string | null;
  "why_fits"?: Array<string>;
  "to_clarify"?: Array<string>;
  "differences"?: Array<string>;
};

export type CatalogueOptions = {
  "cities": Array<string>;
  "categories_by_city": Record<string, Array<string>>;
  "event_formats": Array<string>;
  "languages": Array<string>;
  "calendar_start": string;
  "calendar_end": string;
};

export type ConditionChange = {
  "field": "date" | "budget_kzt" | "duration_hours";
  "from_value": string | number;
  "to_value": string | number;
};

export type ErrorResponse = {
  "error": ApiError;
};

export type HealthResponse = {
  "status"?: "ok";
};

export type InputIssue = {
  "field": string;
  "message": string;
};

export type RecommendationRequest = {
  "city": string;
  "date": string;
  "event_format": "свадьба" | "той" | "корпоратив" | "конференция" | "юбилей" | "день рождения";
  "category": string;
  "budget_kzt": number;
  "duration_hours"?: number | null;
  "language"?: "русский" | "казахский" | "английский" | null;
  "brief"?: string | null;
};

export type RecommendationResponse = {
  "status": "matched" | "category_absent" | "no_eligible";
  "message": string;
  "cards": Array<Card>;
  "reasons": Record<string, number>;
  "ai_mode": "openai" | "nvidia" | "brev" | "fallback" | "not_used";
  "ai_reason"?: "success" | "not_needed" | "local_requested" | "missing_key" | "timeout" | "auth_error" | "rate_limited" | "network_error" | "provider_error" | "invalid_response" | "invalid_evidence";
  "counts"?: SelectionCounts;
  "understanding"?: BriefUnderstanding;
  "alternatives"?: Array<Alternative>;
  "alternatives_note"?: string | null;
  "ranking_mode"?: "tfidf" | "brev" | "not_used";
  "ranking_reason"?: string;
};

export type SelectionCounts = {
  "category_total"?: number;
  "eligible_total"?: number;
  "returned_total"?: number;
  "excluded_total"?: number;
};
